### ISSUE TITLE
Enhance the C++ HelloWorld example to be build as an OSMP FMU

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/sl-1-0-sensor-model-repository-template#16]
**Is your feature request related to a problem? Please describe.**
Currently an minimal C++ example is contained in this repository template. However, test levels 3 and 4 in the [Test Architecture](https://github.com/openMSL/sl-1-5-sensor-model-testing/blob/main/doc/test_architecture.md) need an FMU to be built and run in a co-simulation pipeline.

**Describe the solution you'd like**
A minimal OSMP FMU should be included in this repository, e.g. based on the [OSMPDummySensor](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/tree/master/examples/OSMPDummySensor). Then all test levels including all Github actions with their dependencies and requirements can be demonstrated in this template.

**Comment by jdsika** [comment]
Add error and exception handling best practices

**Comment by ClemensLinnhoff** [comment]
Also add a simple unit test as an example.
