### ISSUE TITLE
Logging does not seem to work

### ISSUE THREAD

**Issue by ClemensLinnhoff** [openMSL/sl-1-0-sensor-model-repository-template#69]
**Describe the bug:**
OSMP Logging functions cannot be enabled.

**Comment by MarcelKe** [comment]
1. The PRIVATE_LOGGING flag in the OSMPConfig.in.h might miss:
![image](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/assets/94037145/4ff6c7f6-cee5-466f-bb7d-84f08fccc1da)

3. I guess it would be nice to copy the resulting OSMPConfig.h with the other source files to the build folder:
 
![image](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/assets/94037145/5ae8f678-1c67-4eee-b5a7-30a515277e02)

(diffferent name in my local fix)

**Comment by ClemensLinnhoff** [comment]
1. I think the PRIVATE_LOGGING flag is not needed in that file. It is set in the CMakeLists. This also aligns with the OSMPDummySensor example.

2. I added the Config header to the FMU sources.

**Comment by MarcelKe** [comment]
1. My bad, I just saw that the PRIVATE_LOGGING flag is only used in the CMakeLists and not in the code itself - The code only checks whether a private logging path is defined.
2.  I can confirm that private logging is working now.
