### ISSUE TITLE
Replace OSI Fieldcheck with OSI-Validation

### ISSUE THREAD

**Issue by jdsika** [openMSL/sl-1-0-sensor-model-repository-template#74]
Release is out: https://github.com/OpenSimulationInterface/osi-validation

* Every repo needs 3 rule sets
* Generic OSI Rules
* Input Rules
* Output Rules

**Comment by ClemensLinnhoff** [comment]
I suggest, that OSI validation should run on every test (integration and behavior). So as soon as an input trace file is used in a test, osi-validation shall automatically check it against the input. And as soon as an output trace file is generated by a test, osi-validation shall automatically check it against the output rules.
So OSI validation becomes sort of a meta test of every test.

**Comment by ClemensLinnhoff** [comment]
Idea: 3 kinds of rule sets:

1. Official ASAM rules
2. Repository rules, one set for input data, one set for output data
3. Test rules: rules that are specific to a certain test

The official ASAM rules are auto-generated by osi-validation

The repository rules shall be defined for the input and output and put in the doc folder alongside a requirements description.

Individual test rules shall be placed in the corresponding test folder. The pipeline shall automatically detect the rules folder for a test and run osi-validation on the test results with the defined rules.
